// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgvjhuux1hCIlWv4OSUiR9JUuYRCUNmV0',
    appId: '1:837756705682:web:b1c6ca8963ea00c17ebf4b',
    messagingSenderId: '837756705682',
    projectId: 'testlogin-e38f7',
    authDomain: 'testlogin-e38f7.firebaseapp.com',
    storageBucket: 'testlogin-e38f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEmfupnqLhLoPmDlrQSNyyhz_7jsUUwVc',
    appId: '1:837756705682:android:0e8da34f9d1177617ebf4b',
    messagingSenderId: '837756705682',
    projectId: 'testlogin-e38f7',
    storageBucket: 'testlogin-e38f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqLkluEFVHkBw1Goaqy65jMp9pbmgKZZA',
    appId: '1:837756705682:ios:646cd0190eabe8397ebf4b',
    messagingSenderId: '837756705682',
    projectId: 'testlogin-e38f7',
    storageBucket: 'testlogin-e38f7.appspot.com',
    iosClientId: '837756705682-ipurcabq4k989mprk32ouarat4lppa5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqLkluEFVHkBw1Goaqy65jMp9pbmgKZZA',
    appId: '1:837756705682:ios:f1801f41aae662547ebf4b',
    messagingSenderId: '837756705682',
    projectId: 'testlogin-e38f7',
    storageBucket: 'testlogin-e38f7.appspot.com',
    iosClientId: '837756705682-j9krmkd49vfckr2qr75mscohll14t2d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginAuth.RunnerTests',
  );
}
